Add docker support
cad-polito-it/ase_riscv_gem5_sim pull request #8
Opened 2024-11-01 17:08 UTC by ezmi234

Added Docker support. The RISC-V container image was built with the latest updated dependencies to ensure a smoother setup and execution.

Note:
Please review the create_predictor.py file. Within the Docker environment, execution proceeds without BTBEntries since the TournamentBP class does not support it as a parameter. To preserve lab configuration compatibility, this behavior is managed using an environment variable, so no existing setup should be affected.

2024-11-04 20:46 UTC, franout commented on setup_default
> +if [[ -n "$IS_DOCKER" ]]; then
I would rather use a different setup_default such as ```setup_default.docker```

2024-11-04 20:46 UTC, franout commented on gem5/create_predictor.py
> +    if os.getenv('IS_DOCKER') != 'true':
i do not understand why docker is affecting the gem5 predictors.
This is something that should not happen

2024-11-04 20:48 UTC, franout commented on gem5/create_predictor.py
@ezmi234  please adjust the spaces compared to the main. It is bad to have diffs based on spaces

2024-11-04 20:49 UTC, franout commented on docker-compose.yml
> +      - IS_DOCKER=true
see setup default commments

2024-11-04 20:50 UTC, franout commented on README.md
> +  - [Installation with Docker](#installation-with-docker)
it is probably more logical to add this in the installation section

2024-11-04 20:52 UTC, franout commented on Dockerfile.riscv
> +RUN cd /opt/riscv-gnu-toolchain && ./configure --prefix=/opt/riscv
the toolchain must be compiled with --enable-multilib. Please see #4

2024-11-04 20:54 UTC, franout commented on Dockerfile.riscv
> +RUN git clone --recursive https://github.com/gem5/gem5 /opt/gem5
be careful. The simulation environment works for the gem5 v22.1.0.0. You are missing the checkout command

2024-11-04 20:55 UTC, franout commented on Dockerfile.konata
why do you need a dockerfile for Konata?
as far i remember, ready to ship executables for konata are already available.

2024-11-04 20:55 UTC, franout commented on DockerDocs.md
duplicate in README.md?

2024-11-04 20:57 UTC, franout commented on README.md
> +Konata is used to open and visualize `.out` files generated in the `results` folder. Before starting the container:
i suggest you to explain better this part.

2024-11-04 20:58 UTC, franout commented on README.md
> +### Running the RISC-V Cross-Compiler
this is incorrect!
the cross compiler is a part of the flow! please read carefully the README.md and the slides.

2024-11-04 20:59 UTC, franout commented on README.md
> +Konata is available in the `konata` container and can be run independently from the gem5 simulation.
i am not getting the point. Why do you want to use a container for konata?

2024-11-04 21:04 UTC, franout requested changes
@ezmi234  thank you for the contribution.
few comments:
- [ ]  please understand the **simulation** flow.
- [ ]  konata is already available in precompiled binaries
- [ ]  i would add an image for the granflow of the container and how things work, somebody could get lost.
- [ ]  i see you used ubuntu22.04, does it work for windows? I think linux-based OSes and mac are fine, the big issue is for windows users.

after you fix those, we can see if it works and merge

2024-11-18 22:23 UTC, closed without merging

2024-11-19 16:31 UTC, franout commented
@ezmi234  do we need to considered the merge as discontinued?

2024-11-19 16:34 UTC, ezmi234 commented
No, ci sto ancora lavorando(oggi ho finito le build delle immagini), domani le faccio vedere in laboratorio. Dovrei aver risolto tutto il difficile